name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  unit_test:
    name: Unit Test
    runs-on: windows-latest
    strategy:
      matrix:
        shell: [powershell, pwsh]
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          # Need at least 2 commits to properly gather changed files for linting
          fetch-depth: 2
      - name: Install and cache test dependencies
        uses: potatoqualitee/psmodulecache@ee5e9494714abf56f6efbfa51527b2aec5c761b8 # v6.2.1
        with:
          modules-to-cache: PSScriptAnalyzer, BuildHelpers, Pester
          shell: ${{ matrix.shell }}
      - name: Run tests
        run: ./test/bin/test.ps1
  e2e_test:
    name: E2E Test
    runs-on: windows-latest
    strategy:
      matrix:
        shell: [powershell, pwsh]
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Run tests
        run: ./.github/scripts/e2e-test.ps1
  ci_iex:
    name: CI IEX Simulation
    runs-on: windows-latest
    strategy:
      matrix:
        shell: [powershell, pwsh]
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Run
        run: |
          Get-Content -Raw -Path ./install.ps1 | Invoke-Expression
          scoop help
